require("prototypes.item.horsemen-armor")
require("prototypes.item.fuel")
require("prototypes.item.ammo")
require("prototypes.item.vehicle")
require("prototypes.item.drill")
require("prototypes.item.furnace")
require("prototypes.item.belt")
require("prototypes.item.substation")
require("prototypes.item.assembling_machine")
require("prototypes.item.turret")
require("prototypes.item.tiles")
require("prototypes.item.fluid")
require("prototypes.item.robots")
require("prototypes.item.beryllium")

require("prototypes.equipment.equipment-grid")

require("prototypes.recipe.horsemen-armor")
require("prototypes.recipe.fuel")
require("prototypes.recipe.ammo")
require("prototypes.recipe.vehicle")
require("prototypes.recipe.drill")
require("prototypes.recipe.furnace")
require("prototypes.recipe.belt")
require("prototypes.recipe.substation")
require("prototypes.recipe.assembling_machine")
require("prototypes.recipe.turret")
require("prototypes.recipe.fluid")
require("prototypes.recipe.robots")
require("prototypes.recipe.beryllium")

require("prototypes.technology.horsemen-armor")
require("prototypes.technology.fuel")
require("prototypes.technology.ammo")
require("prototypes.technology.vehicle")
require("prototypes.technology.drill")
require("prototypes.technology.furnace")
require("prototypes.technology.belt")
require("prototypes.technology.substation")

require("prototypes.entity.vehicle")
require("prototypes.entity.drill")
require("prototypes.entity.furnace")
require("prototypes.entity.belt")
require("prototypes.entity.substation")
require("prototypes.entity.assembling_machine")
require("prototypes.entity.turret")
require("prototypes.entity.robots")

require("prototypes.ores.beryllium")


bobmods.lib.resource.generate(beryllium)
